language: node_js

os:
  - osx
  
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"

before_install:
  - chmod +x ./install.sh

install:
  - ./install.sh
  - npm install

script:
  - npm test

notifications:
  slack: kreativgebiet:MsbOIveN5JdLobZVHat2wdOC
